{{- if not .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
spec:
  suspend: {{ .Values.sync.suspend }}
  template:
    spec:
      {{- if or (eq .Values.sync.from "local") (eq .Values.sync.to "local") }}
      volumes:
        - name: data
          hostPath:
              path: {{ .Values.local.path }}
              type: DirectoryOrCreate
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          command:
            - rclone
            - sync
            - '-vv'
            {{- if eq .Values.sync.from "local" }}
            - '/data'
            {{- else }}
            - '{{ .Values.sync.from }}:'
            {{- end }}
            {{- if eq .Values.sync.to "local" }}
            - '/data'
            {{- else }}
            - '{{ .Values.sync.to }}:'
            {{- end }}
          {{- if or (eq .Values.sync.from "local") (eq .Values.sync.to "local") }}
          volumeMounts:
            - mountPath: /data
              name: data
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
          imagePullPolicy: Always
      restartPolicy: Never
{{- end }}